spring:
  application:
    name: job-service
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
#  cloud:
#    config:
#      enabled: true
#      uri: http://localhost:8081
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:jobsDB
    username: sa
    password: password