server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
      - id: stock-service
        uri: lb://stock-service/
        predicates:
          - Path=/stock/**, /product/**, /seller/**, /stock-sv/**
    discovery:
      locator:
        enable: true